### ISSUE TITLE
fab hl.operations_deploy fails with ImportError: No module named colors

### ISSUE THREAD

**Issue by gsleap** [ICRAR/ngas#12]
Hi,

I'm using ngas v11.0.2 tag and following https://ngas.readthedocs.io/en/latest/install.html#total-system-setup

This is on a clean install of ubuntu18.04 server, with a virtual env built with:
create_venv.sh -f -2 -p /usr/bin/python2.7 /home/mwa/ngas_rt

Have you seen this before? Any ideas on what dependency I am missing? I can't find anything similar on google to help either!

Here's the full output:
**(ngas_rt) mwa@mwacache01:~/ngas_src$ pip freeze**
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
asn1crypto==1.0.1
bcrypt==3.1.7
boto==2.49.0
cffi==1.12.3
cryptography==2.7
enum34==1.1.6
fabric==2.5.0
invoke==1.3.0
ipaddress==1.0.22
paramiko==2.6.0
pycparser==2.19
pycrypto==2.6.1
PyNaCl==1.3.0
six==1.12.0

**(ngas_rt) mwa@mwacache01:~/ngas_src$ fab hl.operations_deploy -u gsleap --set NGAS_USER=mwa**
Traceback (most recent call last):
  File "/home/mwa/ngas_rt/bin/fab", line 10, in <module>
    sys.exit(program.run())
  File "/home/mwa/ngas_rt/local/lib/python2.7/site-packages/invoke/program.py", line 373, in run
    self.parse_collection()
  File "/home/mwa/ngas_rt/local/lib/python2.7/site-packages/invoke/program.py", line 465, in parse_collection
    self.load_collection()
  File "/home/mwa/ngas_rt/local/lib/python2.7/site-packages/fabric/main.py", line 87, in load_collection
    super(Fab, self).load_collection()
  File "/home/mwa/ngas_rt/local/lib/python2.7/site-packages/invoke/program.py", line 696, in load_collection
    module, parent = loader.load(coll_name)
  File "/home/mwa/ngas_rt/local/lib/python2.7/site-packages/invoke/loader.py", line 76, in load
    module = imp.load_module(name, fd, path, desc)
  File "/home/mwa/ngas_src/fabfile/__init__.py", line 30, in <module>
    from . import aws
  File "/home/mwa/ngas_src/fabfile/aws.py", line 29, in <module>
    from fabric.colors import green, red, blue, yellow
ImportError: No module named colors

**Comment by gsleap** [comment]
Thanks Andreas, that did the trick, thank you!
