### ISSUE TITLE
QARCHIVE returns 'NoneType' object has no attribute 'getHostIdList' if mimetype is not found

### ISSUE THREAD

**Issue by gsleap** [ICRAR/ngas#13]
NGAS is doing the right thing, but the message returned could be better, describing that the issue is really that there was no matching mimetype, rather than the reported error about getHostIdList() not being an attribute of NoneType. Workaround is: get my mimetypes right :)

I can reproduce In v11.0.2, with the following qarchive command:
curl -X POST -i -H "Content-Type: application/mimetype_not_existing" --data-binary @test.fits "http://ngashost:7777/QARCHIVE?filename=test.fits"

Returns:
...
Message="'NoneType' object has no attribute 'getHostIdList'" State="ONLINE" Status="FAILURE" SubState="IDLE" Version="11.0.2/2018-11-07T11:00:00"/>

In the log file:
2019-10-15T08:37:36.007 [29022] [       R-6] [ INFO] ngamsServer.ngamsCmdHandling#_get_module:74 Received command: QARCHIVE
2019-10-15T08:37:36.007 [29022] [       R-6] [ERROR] ngamsServer.ngamsServer#reqCallBack:1678 Error while serving request
Traceback (most recent call last):
  File "build/bdist.linux-x86_64/egg/ngamsServer/ngamsServer.py", line 1662, in reqCallBack
    method, path, headers)
  File "build/bdist.linux-x86_64/egg/ngamsServer/ngamsServer.py", line 1756, in handleHttpRequest
    ngamsCmdHandling.handle_cmd(self, reqPropsObj, httpRef)
  File "build/bdist.linux-x86_64/egg/ngamsServer/ngamsCmdHandling.py", line 63, in handle_cmd
    msg = _get_module(srvObj, reqPropsObj).handleCmd(srvObj, reqPropsObj, httpRef)
  File "build/bdist.linux-x86_64/egg/ngamsServer/commands/qarchive.py", line 70, in handleCmd
    do_probe=False, try_to_proxy=True)
  File "build/bdist.linux-x86_64/egg/ngamsServer/ngamsArchiveUtils.py", line 1004, in archiveInitHandling
    srvObj.getCfg().getStreamFromMimeType(mimeType).getHostIdList()):
AttributeError: 'NoneType' object has no attribute 'getHostIdList'
2019-10-15T08:37:36.007 [29022] [       R-6] [ INFO] ngamsServer.ngamsServer#send_status:335 Returning status FAILURE with message 'NoneType' object has no attribute 'getHostIdList' and HTTP code 400
2019-10-15T08:37:36.008 [29022] [       R-6] [ INFO] ngamsServer.ngamsServer#send_data:304 Sending 366 bytes of data of type text/xml and headers {}

Looking at the code, the part that fails is in ngamsArchiveUtils.py:
if (try_to_proxy and
        srvObj.getCfg().getStreamFromMimeType(mimeType).getHostIdList()):
    ... 

getStreamFromMimeType(mimeType) returns None, presumably because the mimeType was not found in the NGAS config, and then getHostIdList() is called on that returned None object. So maybe check for the return value of getStreamFromMimeType(mimeType) first and only if it is not None to call getHostIdList().

**Comment by rtobar** [comment]
This has now been fixed on the `master` branch, a more "Unknown mime type: <name>" error is now returned to the user instead of the older, cryptic message. A new unit test ensures this is the case by checking that "<name>" is present in the error message returned to the user (which then hints that the error message refers to this missing type instead of being something else entirely).
