### ISSUE TITLE
NGAMS python client --serer option bug

### ISSUE THREAD

**Issue by smclay** [ICRAR/ngas#60]
I get the following bug when attempting to use the `--server` command line option for the NGAMS python client

```
$ /usr/bin/ngams3PClient --servers "my-server:7777" --status /path/to/response.xml --timeout 5 --file-uri /path/to/file.txt --mime-type text/data ARCHIVE
Traceback (most recent call last):
  File "/usr/bin/ngams3PClient", line 11, in <module>
    load_entry_point('ngamsPClient==11.0', 'console_scripts', 'ngamsPClient')()
  File "/usr/lib/python3.6/site-packages/ngamsPClient/ngamsPClient.py", line 887, in main
    servers = [(host, int(port)) for s in opts.servers.split(',') for host,port in s.split(':')]
  File "/usr/lib/python3.6/site-packages/ngamsPClient/ngamsPClient.py", line 887, in <listcomp>
    servers = [(host, int(port)) for s in opts.servers.split(',') for host,port in s.split(':')]
ValueError: too many values to unpack (expected 2)
```

**Comment by rtobar** [comment]
Thanks @smclay for reporting, there was indeed a bug in the parsing of the value given via the `--servers` command line flag. This has now been fixed and merged to `master`, and a new unit test has been added to make sure this doesn't break in the future.
