### ISSUE TITLE
Checksum calculation mismatch failure on python 3

### ISSUE THREAD

**Issue by smclay** [ICRAR/ngas#69]
I am running a mirroring test from an legacy NGAS cluster to a NGAS github cluster. I get the following logging error message...
```
2021-12-12T11:33:42.993 [26176] [Thread-314] [ ERROR] ngamsPlugIns.ngamsCmd_MIRREXEC#process_mirroring_tasks:500 Failed to fetch test_sample_1000_0775.txt
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/ngamsPlugIns/ngamsCmd_MIRREXEC.py", line 496, in process_mirroring_tasks
    ngamsCmd_MIRRARCHIVE.handleCmd(ngams_server, request_properties)
  File "/usr/lib/python3.6/site-packages/ngamsPlugIns/ngamsCmd_MIRRARCHIVE.py", line 117, in handleCmd
    __handle_command(ngams_server, request_properties)
  File "/usr/lib/python3.6/site-packages/ngamsPlugIns/ngamsCmd_MIRRARCHIVE.py", line 156, in __handle_command
    staging_filename, start_byte)
  File "/usr/lib/python3.6/site-packages/ngamsPlugIns/ngamsCmd_MIRRARCHIVE.py", line 105, in save_in_staging_file
    block_size, start_byte)
  File "/usr/lib/python3.6/site-packages/ngamsPlugIns/ngamsCmd_HTTPFETCH.py", line 185, in save_to_file
    raise ngamsFailedDownloadException.FailedDownloadException(msg)
ngamsPlugIns.ngamsFailedDownloadException.FailedDownloadException: 'checksum mismatch: source=-942573743, received=3352393553'
```
This only happens when I run the NGAS github cluster on python 3. When running on python 2 the checksum calculations match.

**Comment by rtobar** [comment]
That's because of a change on how crc32 is represented under the hood between ptyhon2 and 3. That's why we introduced the `crc_info` structures, which take this into account. For example, this is how we check the checksum in the ARCHIVE/QARCHIVE command:

https://github.com/ICRAR/ngas/blob/eb83678bd9f62bb11719e3277a8b04424ec5effe/src/ngamsServer/ngamsServer/ngamsArchiveUtils.py#L247

Note also thatt this old crc32 checksum behavior means if a checksum was calculated and written into the database with python2, then it might cause the file checker thread to fail if you are running the system now with python3. This is why I named this variant `CHECKSUM_CRC32_INCONSISTENT` in the code, why you need to use these special `equals` method, and why I introduced the "crc32z" variant (which could have been better named probably). All details are here:

https://github.com/ICRAR/ngas/blob/eb83678bd9f62bb11719e3277a8b04424ec5effe/src/ngamsServer/ngamsServer/ngamsFileUtils.py#L812-L901

**Comment by smclay** [comment]
Thanks @rtobar. I have applied a fix following your suggestion. It now passes my test.

**Comment by rtobar** [comment]
Merged, thanks!
